// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SW.DAL;

#nullable disable

namespace SW.DAL.Migrations
{
    [DbContext(typeof(SWDBContext))]
    partial class SWDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.22");

            modelBuilder.Entity("SW.Models.Citoyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspeceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MereBiologiqueID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PereBiologiqueID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EspeceId");

                    b.HasIndex("MereBiologiqueID");

                    b.HasIndex("PereBiologiqueID");

                    b.ToTable("Citoyens");
                });

            modelBuilder.Entity("SW.Models.Espece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Longevite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Majorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Espece");
                });

            modelBuilder.Entity("SW.Models.Citoyen", b =>
                {
                    b.HasOne("SW.Models.Espece", "Espece")
                        .WithMany()
                        .HasForeignKey("EspeceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SW.Models.Citoyen", "MereBiologique")
                        .WithMany()
                        .HasForeignKey("MereBiologiqueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SW.Models.Citoyen", "PereBiologique")
                        .WithMany()
                        .HasForeignKey("PereBiologiqueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espece");

                    b.Navigation("MereBiologique");

                    b.Navigation("PereBiologique");
                });
#pragma warning restore 612, 618
        }
    }
}
